### ISSUE TITLE
Error in mnist_example.py about the Qiskit

### ISSUE THREAD

**Issue by caitaozhan** [mit-han-lab/torchquantum#101]
Hi Hanrui, 

I am running the _mnist_example.py_ and I am having the following error when running on Qiskit simulator and real Quantum Computers (before line 211 in _mnist_example.py_ is good, but after line 211 run into errors). I am using the latest version of the code. Any clue why this happens? 
```
[2023-03-27 23:21:22.055] Job failed because 'Number of input circuits does not match number of input parameter bind dictionaries', rerun now.
```
Thanks for your help!
Caitao

**Comment by Hanrui-Wang** [comment]
Hi Caitao,

Thanks a lot for the feedback! This is because a bug in Qiskit parameterization. We have find a workaround to not use the qiskit parameter binding. 

Please have a look at the updated mnist_example.py. Right now it uses the operations recorded in the qdev to convert tq model to qiskit. And it expands the encoder part to create fixed gate circuit so no binding is needed. 

Please let me know for any questions!

Attached the result i just ran:

```
[2023-03-29 02:55:06.882] Only use the front 75 images as TEST set.
Epoch 1:
0.005 0.5862550139427185
valid set accuracy: 0.8157676348547718
valid set loss: 0.5728925466537476
Epoch 2:
0.00250.5613003373146057
valid set accuracy: 0.8149377593360996
valid set loss: 0.5511690974235535
test set accuracy: 0.6533333333333333
test set loss: 0.626448392868042

Test with Qiskit Simulator
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 75/75 [00:04<00:00, 18.24it/s]
Job Status: job has successfully run
Job Status: job has successfully run
Job Status: job has successfully run
Job Status: job has successfully run
Job Status: job has successfully run
test set accuracy: 0.6666666666666666
test set loss: 0.6252803337740171

Test on Real Quantum Computer ibmq_lima
ibmqfactory.load_account:WARNING:2023-03-29 02:55:33,169: Credentials are already in use. The existing account in the session will be replaced.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 75/75 [00:05<00:00, 12.69it/s]
Job Status: job has successfully run
test set accuracy: 0.6
test set loss: 0.6596525936855245
```

**Comment by caitaozhan** [comment]
Hi Hanrui,

Thanks for the update. I updated to the newest version, but I am still getting errors. The error occurs in line 101 of _mnist_example.py_: **Trying to compose with another QuantumCircuit which has more 'in' edges.**
```
  File "/home/caitao/Project/torchquantum/examples/simple_mnist/mnist_example.py", line 101, in forward
    assembled_circs = qiskit_assemble_circs(
  File "/home/caitao/anaconda3/lib/python3.8/site-packages/torchquantum/plugins/qiskit_plugin.py", line 40, in qiskit_assemble_circs
    circ = encoder.compose(fixed_layer).compose(measurement)
  File "/home/caitao/anaconda3/lib/python3.8/site-packages/qiskit/circuit/quantumcircuit.py", line 922, in compose
    raise CircuitError(
qiskit.circuit.exceptions.CircuitError: "Trying to compose with another QuantumCircuit which has more 'in' edges."
```

Don't understand what it means. Could you please help?

Thanks,
Caitao

**Comment by Hanrui-Wang** [comment]
Hi Caitao,

This is because in when compose the circuit, `encoders` and `fixed_layer` don't have classical registers while `measurement` has. This can work for old versions of qiskit. I have modified the function to explicitly add classical registers to `encoders` and `fixed_layer` before compose in the latest version. Please try it out.

**Comment by caitaozhan** [comment]
Hi Hanrui,

It works now! But I have to copy the function _qiskit_assemble_circs(encoders, fixed_layer, measurement)_  to _mnist_example.py_. If not copied, the code will call the old function in the package tq.plugins, which is not updated yet.

Thanks a lot,
Caitao

**Comment by Hanrui-Wang** [comment]
Hi Caitao,

Great! I think the reason for that is the torchquantum is installed with pip or the --editable is not used when install from source.

Could you try to uninstall the current torchquantum and install with the follow way:


```
git clone https://github.com/mit-han-lab/torchquantum.git
cd torchquantum
pip install --editable .
```

In this case, the import will be locating the files in the torchquantum folder so when you update the code in tq, it can be used instantly. 

Let me know if you have any questions!

**Comment by caitaozhan** [comment]
Hi Hanrui,

All issues are solved. Thank you for your help!

Caitao

**Comment by Hanrui-Wang** [comment]
Great! my pleasure
