### ISSUE TITLE
Request to add grouping for pauli strings

### ISSUE THREAD

**Issue by Kyriection** [mit-han-lab/torchquantum#115]
Thanks for the fantastic codebase. 

Can we add a new feature to group the Pauli strings when conducting measurements in VQE? Since part of the Pauli strings can be measured simultaneously, we may group them together to make measurement more efficient.

**Comment by Hanrui-Wang** [comment]
Hi Zhenyu,

Please see https://github.com/mit-han-lab/torchquantum/blob/97425bc0c3deaf9eb98a2c2d6f0d67f310342940/torchquantum/measurement.py#L107 for the measurement with grouping function.

**Comment by Kyriection** [comment]
Hi Hanrui, 

Thanks for addressing this issue!
