### ISSUE TITLE
How to obtain VQE results given a molecule and a QuantumCircuit?

### ISSUE THREAD

**Issue by jinleic** [mit-han-lab/torchquantum#116]
I wonder if it is possible to support QuantumCircuit that is not a parameterized Circuit.

For example,

a = QuantumCircuit(2)
a.h(0)
a.h(1)
a.rx(0,0)
a.rx(0,1)

vqe_res = func(molecule, a)

**Comment by Hanrui-Wang** [comment]
Hi Jinglei,

Please have a look at the new script:
https://github.com/mit-han-lab/torchquantum/blob/dev/examples/simple_vqe/new_simple_vqe.py

**Comment by jinleic** [comment]
The codes work perfectly, thanks again for the help!
