### ISSUE TITLE
Pulse level simulation and variational circuits

### ISSUE THREAD

**Issue by Hanrui-Wang** [mit-han-lab/torchquantum#132]
In order to support more pulse level functionalities and train variational circuit on pulse level, we need your help on a GPU-accelerated pulse simulator. The principle of that is to solve the Schrödinger equation related to the system Hamiltonian. This process will be refined into a multitude of ordinary differential equations (ODEs). The process of solving these ODEs will be implemented with PyTorch and will support GPU-accelerated processing, making the entire pulse simulation process more efficient.

With the pulse simulation, we will be able to train parameterized quantum pulses. The standard shape of the pulse is optional and variable. The shape of the pulse, amplitude, and duration will be considered as trainable parameters in parameterized quantum pulses.
Here are several steps:

- [ ]  Implement the pulse simulator using PyTorch, and design routines to decompose the Schrödinger equation into a set of ODEs that can be efficiently processed. Implement efficient methods to solve these ODEs using both GPU and CPU.
- [ ] Create an API that enables users to define and train parameterized quantum pulses within the VQA framework, allowing for customization of pulse shape, amplitude, and duration.
- [ ] Implement training routines that take pulse shape, amplitude, and duration as trainable parameters, using the appropriate optimization algorithms. Implement functionality to ensure that the pulse parameters are updated dynamically during the training process based on feedback from the VQA.

Please don't hesitate to ask and discuss here for any questions!

**Comment by neogyk** [comment]
Dear all, 

I would like to work on this issue as a part of Unitary Hack. Could you please assign it to me?

Best regards,
Leonid Didukh

**Comment by Hanrui-Wang** [comment]
Hi Leonid,

Thank you for your interest, I have assigned you.

**Comment by Amana-L** [comment]
Hi @neogyk, are you still working on this? 

It seems interesting and I'd like to give it a shot.

If you're already in progress, I'd be happy to lend a hand.

Thanks,
Amana

**Comment by Hanrui-Wang** [comment]
Congrats @jinglei for successfully merging the pull request!

**Comment by Hanrui-Wang** [comment]
Since the UnitaryHack comes to the end, I will close this one but feel free to continue to add more functionality to the pulse module! Thank you all for the participation!
