### ISSUE TITLE
Files from PyPi are different from the main and dev branches  

### ISSUE THREAD

**Issue by moustafa7zada** [mit-han-lab/torchquantum#148]
for example, the `expval_joint_sampling` and `expval_joint_sampling_grouping` form [measurment.py](https://github.com/mit-han-lab/torchquantum/blob/main/torchquantum/measurement.py) are missing when you install torchqunautm via `pip install torchquantum`

**Comment by GenericP3rson** [comment]
Hi! Thanks for opening the issue!

To get the most up-to-date version of TorchQuantum, you have to install it from source, as described in the [README Installation](https://github.com/mit-han-lab/torchquantum#installation):

```
git clone https://github.com/mit-han-lab/torchquantum.git
cd torchquantum
pip install --editable .
```

We will also be sure to update the pip version soon!

**Comment by GenericP3rson** [comment]
We just updated the PyPi for the most recent release!
