### ISSUE TITLE
Issue while making ipynote book for mnsit_example

### ISSUE THREAD

**Issue by Hanrui-Wang** [mit-han-lab/torchquantum#157]
> > I get this issue while making ipynote book for mnsit_example
> > don't able to resolve it. @Hanrui-Wang any suggestion upon how I move forward ` --------------------------------------------------------------------------- SystemExit Traceback (most recent call last) in <cell line: 1>() 1 if **name** == "**main**": ----> 2 main()
> > 3 frames [/usr/lib/python3.10/argparse.py](https://localhost:8080/#) in exit(self, status, message) 2591 if message: 2592 self._print_message(message, _sys.stderr) -> 2593 _sys.exit(status) 2594 2595 def error(self, message):
> > SystemExit: 2 `
> 
> Hi [MihirsinhChauhan](https://github.com/MihirsinhChauhan),
> 
> Could you provide more information about which file you are running and the full error message?

I have runned this eample `examples/simple_mnist/mnist_example.py`.
full traceback is 
---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
[<ipython-input-9-972361fa1b80>](https://localhost:8080/#) in <cell line: 1>()
      1 if __name__ == "__main__":
----> 2     main()

3 frames
[<ipython-input-8-81317c857991>](https://localhost:8080/#) in main()
     12     )
     13 
---> 14     args = parser.parse_args()
     15 
     16     if args.pdb:

[/usr/lib/python3.10/argparse.py](https://localhost:8080/#) in parse_args(self, args, namespace)
   1846         if argv:
   1847             msg = _('unrecognized arguments: %s')
-> 1848             self.error(msg % ' '.join(argv))
   1849         return args
   1850 

[/usr/lib/python3.10/argparse.py](https://localhost:8080/#) in error(self, message)
   2604         self.print_usage(_sys.stderr)
   2605         args = {'prog': self.prog, 'message': message}
-> 2606         self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

[/usr/lib/python3.10/argparse.py](https://localhost:8080/#) in exit(self, status, message)
   2591         if message:
   2592             self._print_message(message, _sys.stderr)
-> 2593         _sys.exit(status)
   2594 
   2595     def error(self, message):

SystemExit: 2

_Originally posted by @MihirsinhChauhan in https://github.com/mit-han-lab/torchquantum/issues/135#issuecomment-1589859850_

**Comment by GenericP3rson** [comment]
I think this error is coming from the fact that one cannot use argparser in a notebook. There’s a whole thread on alternatives for passing parameters here: https://stackoverflow.com/questions/30656777/how-to-call-module-written-with-argparse-in-ipython-notebook 

Personally, I think that the best way to deal with this is just declare constants on the top of the notebook instead of dealing with parameter-passing.

With that said, I think we can safely close this issue. We definitely open it again though if others run into something similar!
