### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by GenericP3rson** [mit-han-lab/torchquantum#161]
Looks like there's a missing dependency when installing the library.

```
ModuleNotFoundError: No module named 'torchdiffeq'
```

To replicate:

```
git clone https://github.com/mit-han-lab/torchquantum.git
cd torchquantum
pip install --editable .

echo "import torchquantum" >> test.py
python test.py
```

Looks like it's an error from the import [here](https://github.com/mit-han-lab/torchquantum/blob/03a790c0a6e17dcdbc94fa0a83c78fae094dafc7/torchquantum/pulse/sesolve/sesolve.py#L5). I can open a PR, but I'm also not completely sure what is the oldest version of `torchdiffeq` that is compatible.

**Comment by Hanrui-Wang** [comment]
I have merged, thanks a lot for the contribution!
