### ISSUE TITLE
inconvenient to run VQE example

### ISSUE THREAD

**Issue by royess** [mit-han-lab/torchquantum#19]
I find it not very convenient to run VQE example. If I run `python examples/vqe/train.py` directly, I will get an error message
```
......
    from examples.vqe import builder
ModuleNotFoundError: No module named 'examples.vqe'
```  

But `python -c "from examples.vqe import builder"` works fine, which is strange to me.

And my current way to run the script is by opening a python REPL and running
```
from examples.vqe import train
import sys
sys.argv.append('examples/vqe/vqe_configs.yml')
train.main()
```

I wonder whether I can do it in a simpler way. Or there is a need to modify codes.

**Comment by abclzr** [comment]
Try this command `export PYTHONPATH=.` under torchquantum’s root folder.

**Comment by royess** [comment]
It works. Thanks!
