### ISSUE TITLE
Allow IBMQ Credentials for GitHub Actions Tests (to automatically test qiskit plugins)

### ISSUE THREAD

**Issue by GenericP3rson** [mit-han-lab/torchquantum#207]
Currently, the tests automatically skip the qiskit plugins tests because it some of the functions require IBMQ Credentials. There ought to be someway to automatically login with the credentials on GitHub Actions and therefore be able to successfully run the test.

**Comment by not-lain** [comment]
@GenericP3rson have you tried defining the credentials in the github repo secrets ? 
![image](https://github.com/mit-han-lab/torchquantum/assets/70411813/e0c9402a-8b35-4a43-a349-afdb59b12de8)


you can then load your credentials using something similar to this 
https://github.com/not-lain/loadimg/blob/34216f667360b2e08752457cd4f74e5388e0e86e/.github/workflows/python-publish.yml#L39

**Comment by GenericP3rson** [comment]
Hi, thanks for the suggestion! This is actually resolved now.
