### ISSUE TITLE
Code for reproducing QuantumNAS results missing

### ISSUE THREAD

**Issue by SashwatAnagolum** [mit-han-lab/torchquantum#21]
The .py and .yml files referenced in the shell scripts used to reproduce the results from the QuantumNAS paper seem to be missing - when running the Colab notebooks, I always run into this error: 

`can't open file 'examples/train.py': [Errno 2] No such file or directory`

I tried searching for the files in the repo manually, but could not find the .py or the .yml files anywhere.

**Comment by Hanrui-Wang** [comment]
Hi Sashwat,

Thanks for your interest in our work! You can find the files in the `allconfigs` branch. We are currently refactoring the codebase and we will also provide refactored QuantumNAS code soon.

**Comment by SashwatAnagolum** [comment]
Awesome, thank you!
