### ISSUE TITLE
removing dependency in requirements.txt

### ISSUE THREAD

**Issue by Hanrui-Wang** [mit-han-lab/torchquantum#243]
I am removing furo @ git+https://github.com/frogcjn/torchquantum-doc-furo-theme.git because pypi cannot depend on this direct dependency, could you @GenericP3rson check if any additional dependency should added?

**Comment by GenericP3rson** [comment]
I think this should be fine so as long as furo is in the `docs/requirements.txt`. I’ll be sure to look into it more in case there’s anything else to worry about!

**Comment by GenericP3rson** [comment]
Looked into this and we should be fine without the dependency!
