### ISSUE TITLE
But in example mnist_clifford_qnn.py 

### ISSUE THREAD

**Issue by yezhuoyang** [mit-han-lab/torchquantum#245]
When I tried to run the example:

\torchquantum\examples\clifford_qnn\mnist_clifford_qnn.py

There is an error:

![image](https://github.com/mit-han-lab/torchquantum/assets/34168020/552d5e54-819f-405e-b46c-71ba3033d291)

**Comment by yezhuoyang** [comment]
It seems to be a bug in the encoding function:

![image](https://github.com/mit-han-lab/torchquantum/assets/34168020/63efeb55-5012-4cb8-9f76-2ea1aafa18b2)

**Comment by GenericP3rson** [comment]
I’m going to close this since it’s a duplicate of #213. It’s on our radar to get fixed!
