### ISSUE TITLE
NameError: name 'Op2QAllLayer' is not defined

### ISSUE THREAD

**Issue by yezhuoyang** [mit-han-lab/torchquantum#246]
In the "torchquantum\examples\param_shift_onchip_training\param_shift.py" example, there is a bug:

![image](https://github.com/mit-han-lab/torchquantum/assets/34168020/f7989efd-f4ac-4d1d-8d99-3deb838fdbc1)

In the class file 

torchquantum\torchquantum\layer\layers\seth_layer.py

Op2QAllLayer and Op1QAllLayer are used but not imported.

Op1QAllLayer can be imported from layer.py,
but Op2QAllLayer is not defined in the module.

![image](https://github.com/mit-han-lab/torchquantum/assets/34168020/73284be8-8579-4e4d-89fd-006aa9131225)

**Comment by yezhuoyang** [comment]
Same kind of issue when I run

torchquantum\examples\quanvolution\quanvolution_trainable_quantum_layer.py 


![image](https://github.com/mit-han-lab/torchquantum/assets/34168020/2eeb3214-4d45-4e2b-9f4e-e98f3ec701f8)

**Comment by GenericP3rson** [comment]
Looked into this, and I think your branch may be outdated. I recommend merging the latest updates from dev!
