### ISSUE TITLE
running the example

### ISSUE THREAD

**Issue by badreddinemerabet** [mit-han-lab/torchquantum#251]
ModuleNotFoundError Traceback (most recent call last)
in <cell line: 2>()
1 import torchquantum as tq
----> 2 import torchquantum.functional as tqf
3
4 qdev = tq.QuantumDevice(n_wires=2, bsz=5, device="cpu", record_op=True) # use device='cuda' for GPU
5

ModuleNotFoundError: No module named 'torchquantum.functional'

I have the error also, and I didn't manage to solve it

Also I tried the colab notebook u post

**Comment by GenericP3rson** [comment]
Hi! Thanks for the opening the issue. There was an API change recently, and I’ll deep dive what’s exactly is going on here by Saturday. In the meantime, if you’re looking for hello-world examples, we run several examples through for our tests, so anything in this list should be functional: https://github.com/mit-han-lab/torchquantum/blob/b7f8c36db0fed0f5336ec15e615825780487249a/.github/workflows/functional_tests.yaml#L43

I personally think mnist is a pretty good place to start. Let me know if you have any questions and will get this done shortly!

**Comment by badreddinemerabet** [comment]
i want to use the QNN for my own data for image classification

**Comment by GenericP3rson** [comment]
I see. With a fresh install, I cannot replicate the issue, interestingly.

**Comment by badreddinemerabet** [comment]
i fix it, thank you very much

**Comment by GenericP3rson** [comment]
Awesome, could you post the solution? It might help others running into the same issue!

**Comment by badreddinemerabet** [comment]
I created a new environment and downgraded all the packages to approximately the 2023 release.
