### ISSUE TITLE
Missing "qiskit.providers.backend"... very strange !

### ISSUE THREAD

**Issue by Jesshuan** [mit-han-lab/torchquantum#253]
Hello,
And thanks for torch quantum !...

I applied the new requirements.txt provided one hour ago... and I've a new problem during torchquantum importation :

File ~/miniconda3/envs/retnet_experiment/lib/python3.11/site-packages/torchquantum/device/devices.py:30
...
---> 23 from qiskit.providers.backend import BackendV1 as Backend
     24 from qiskit.providers.provider import ProviderV1 as Provider
     25 from qiskit.providers.exceptions import QiskitBackendNotFoundError

ModuleNotFoundError: No module named 'qiskit.providers.backend'

All my qiskit versions :

pip list | grep qiskit
qiskit                        0.46.1
qiskit-aer                   0.13.3
qiskit-ibm-runtime            0.20.0
qiskit-terra                  0.46.1

In source code of quiskit-aer 0.13.0 BackendV1 exists ! It's very strange...

**Comment by GenericP3rson** [comment]
Interesting, it’s working fine with the same qiskit versions on this notebook: https://colab.research.google.com/drive/16lKbM4kQXZgjMMDNsuyDDbUoRbCVJ7Zf?usp=sharing.

Maybe a fresh install could help? I'll doing some digging on what I can do, but in the meantime, feel free to use the above notebook to work on Colab if that’s feasible for you.

Also, as an FYI, a task that’s on my radar is separating out the qiskit aspects from tq so we no longer have the dependency. Unfortunately, it might be 1-2 months till I officially get that rolled out.

**Comment by Jesshuan** [comment]
Thanks,
And sorry : with a fresh install... it's work !

**Comment by Hanrui-Wang** [comment]
Great! Thank you [GenericP3rson](https://github.com/GenericP3rson) for helping solve this
