### ISSUE TITLE
Enhance the Pulse-Level Simulation

### ISSUE THREAD

**Issue by Hanrui-Wang** [mit-han-lab/torchquantum#260]
We want to continue working to build up our pulse-level simulation. You can reference an example from [QuTip](https://qutip.org/docs/4.6/guide/qip/qip-processor.html) and see our current implementation in pulse.

**Comment by Packman2002** [comment]
@Hanrui-Wang I would like to implement the quantum annealing algorithm using pulse-simulation and add it to the torch-quantum repo. I did not find any support for this, please let me know if you think this is possible and how to proceed?

**Comment by adilnaut** [comment]
I'd love to try implementing Monte Carlo sampling of quantum trajectories based on qutip.mcsolve - the very minimal example.
