### ISSUE TITLE
Make TQ Compatible with Qiskit ≥1.0.0

### ISSUE THREAD

**Issue by GenericP3rson** [mit-han-lab/torchquantum#262]
Currently, TQ is not compatible with Qiskit 1.0.0, specifically we still depend on the aer module. For this task, please make TQ compile with the latest version of Qiskit! It’s even better if you remove all of the warnings during compilation!

**Comment by maxwell04-wq** [comment]
I'd like to work on this issue.

**Comment by GenericP3rson** [comment]
Hi! Thanks for the interest, but it unfortunately looks like we already have a PR that I'll merge in soon. Please feel free to check out other issues though!! We look forward to your contributions!

**Comment by king-p3nguin** [comment]
Hi, I am working on this issue and would like to be assigned after successfully merging the PR.
