### ISSUE TITLE
Supporting Additional Features for tq2qiskit and qiskit2tq

### ISSUE THREAD

**Issue by GenericP3rson** [mit-han-lab/torchquantum#263]
Our tq2qiskit and qiskit2tq conversions currently do not have full support for converting between qiskit and torchquantum circuits. In this task, we need your help adding new features to these operations. For example, a place to start can be allowing TQ’s qiskit2tq to parse Qiskit’s ParameterExpression.

**Comment by Youngcius** [comment]
Hi @GenericP3rson, I'd like to work on this.

**Comment by GenericP3rson** [comment]
Added, good luck! When you know what features you would like to add, please comment them in this thread!

**Comment by king-p3nguin** [comment]
Hi, I would also like to work on this issue.
