### ISSUE TITLE
Will it be possible to run torchquantum code on quantum computer, when it’s built?

### ISSUE THREAD

**Issue by jmaczan** [mit-han-lab/torchquantum#265]
Hi, thanks for creating this project. Does it might serve for simulations only or maybe it will be possible to run torchquantum code on a quantum computer, once it’s built?

**Comment by GenericP3rson** [comment]
Hey! Yes, you can directly run TQ code on real quantum computers using IBM's API! For an example, you can check out `examples/mnist/mnist.py` which can be run on a quantum computer if you connect IBMQ credentials. Feel free to reach out with any questions with that functionality!

**Comment by GenericP3rson** [comment]
(I'll mark this as closed for now, but if you have further questions, feel free to follow up either here or in a new issue!)

**Comment by jmaczan** [comment]
Wow, there is really an API for running code on a real quantum computer? I’m coming from traditional CS and it blows my mind, I wasn’t aware that this is the case. Could you recommend some resources on this topic? How is it possible and how do they do this?

**Comment by GenericP3rson** [comment]
Yup, you can check out IBMQ's API/resources to learn more: https://quantum.ibm.com/

I guess this page specifically focuses more on actual deployment: https://docs.quantum.ibm.com/run

There should be a ton of resources to explore there!

**Comment by jmaczan** [comment]
Thank you so much!
