### ISSUE TITLE
Cannot use Qiskit simulation when running example1

### ISSUE THREAD

**Issue by yzr-mint** [mit-han-lab/torchquantum#39]
I tried to run` torchquantum-master\artifact\example1\mnist_example.py`, but I ran into some trouble when doing qiskit simulation, too.

Because the flie "examples.core.datasets" is missing, I copied it from the file from [https://zenodo.org/record/5787244#.YbunmBPMJhE.](url)(\torchquantum-master\examples\core\datasets).
To avoid BrokenPipeError, I reset the "num_workers" in line 152 to 0.

After these messages:
```
Test with Qiskit Simulator
[2022-10-20 14:33:05.579] Before transpile: {'depth': 36, 'size': 77, 'width': 8, 'n_single_gates': 52, 'n_two_gates': 21, 'n_three_more_gates': 0, 'n_gates_dict': {'ry': 19, 'rz': 18, 'rx': 13, 'cx': 20, 'crx': 1, 'h': 1, 'sx': 1, 'measure': 4}}
[2022-10-20 14:33:06.257] After transpile: {'depth': 31, 'size': 61, 'width': 8, 'n_single_gates': 37, 'n_two_gates': 20, 'n_three_more_gates': 0, 'n_gates_dict': {'ry': 11, 'rz': 7, 'rx': 6, 'cx': 20, 'u3': 11, 'u1': 2, 'measure': 4}}
```
an error occurred, saying "need at least one array to stack". the details are in the file "errorlog1"

I also tried to add ", parallel=False" and modify the file qiskit/assembler/assemble_circuits.py as the Issue#9 does, but another error occurred, the details are in the file "errorlog2"

The version information is as follow,
```
>>> import qiskit
>>> qiskit.version.QiskitVersion()
{'qiskit-terra': '0.19.2', 'qiskit-aer': '0.10.3', 'qiskit-ignis': '0.7.0', 'qiskit-ibmq-provider': '0.18.3', 'qiskit-aqua': '0.9.5', 'qiskit': '0.34.2', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}
```
and I'm running the code under python 3.9.

By the way, I tried the code in [https://zenodo.org/record/5787244#.YbunmBPMJhE.](url). The same problem occurred.
I wonder how to deal with it. Any help would be greatly appreciated.

[errorlog1.txt](https://github.com/mit-han-lab/torchquantum/files/9827330/errorlog1.txt)
[errorlog2.txt](https://github.com/mit-han-lab/torchquantum/files/9827332/errorlog2.txt)

**Comment by Hanrui-Wang** [comment]
Hi yzr-mint,

Thank you for your feedback, I think that may because of the version mismatch between the torchquantum-master\artifact\example1\mnist_example.py and the current QiskitProcessor. Could you try to run the new code in examples folder?  https://github.com/mit-han-lab/torchquantum/blob/master/examples/simple_mnist/mnist_example_no_binding.py

Please let me know if that works. Thanks!

**Comment by yzr-mint** [comment]
It works! Thanks!
