### ISSUE TITLE
A simple way to improve the regression example

### ISSUE THREAD

**Issue by caitaozhan** [mit-han-lab/torchquantum#48]
https://github.com/mit-han-lab/torchquantum/blob/7122388a3d58d5b6c48db44fbd4b27198941ed2f/examples/regression/run_regression.py#L138

In this example, after the measurement, you get 3 numbers (_output_all_.shape = [bsz, 3]). 
However, in the loss function, only the 2nd number is utilized, i.e., [:, **1**]. This leads to **poor performance**.
A simple fix can significantly improve the performance (I already tested).
1. Add **res = self.linear(res)** to the last step of the self.forward() function, where  **self.linear = nn.torch.Linear(self.n_wires, 1)**
2. The _targets_ need to unsqueeze(dim=-1) so the dimension of _outputs_all_ and _targets_ match

BTW: I have been playing around with torchquantum recently. It is a very good tool.

**Comment by Hanrui-Wang** [comment]
Hi Caitao,

Thanks a lot for the suggestions! I have add that as an option in the regression example, the linear layer will be added with command below:

`python run_regression.py --addfc`
