### ISSUE TITLE
Cannot use qiskit simulation when running mnist_example.py

### ISSUE THREAD

**Issue by royess** [mit-han-lab/torchquantum#9]
I tried to run `mnist_example.py` with IBM Q token already set. But I ran into trouble when doing qiskit simulation. The line is

```python
valid_test(dataflow, 'test', model, device, qiskit=True)
```
I think the execution should be fast, but it got stuck after the following messages：

```
Test with Qiskit Simulator
[2022-03-22 22:36:14.573] Before transpile: {'depth': 32, 'size': 77, 'width': 8, 'n_single_gates': 62, 'n_two_gates': 11, 'n_three_more_gates': 0, 'n_gates_dict': {'ry': 19, 'rz': 24, 'rx': 17, 'cx': 10, 'crx': 1, 'h': 1, 'sx': 1, 'measure': 4}}
[2022-03-22 22:36:14.864] After transpile: {'depth': 23, 'size': 49, 'width': 8, 'n_single_gates': 33, 'n_two_gates': 12, 'n_three_more_gates': 0, 'n_gates_dict': {'ry': 8, 'rz': 7, 'rx': 4, 'cx': 12, 'u1': 2, 'u3': 11, 'u2': 1, 'measure': 4}}
```

I interrupted the program using `ctrl+c` after 2-3 minutes, getting a very long error log for interrupting multiprocessing. I want to know what causes that trouble and how to deal with it.

Thank!

---

I am using torchquantum master branch, qiskit 0.19.2.

[error_log.txt](https://github.com/mit-han-lab/torchquantum/files/8325312/error_log.txt)

**Comment by Hanrui-Wang** [comment]
Hi Rabqubit,

Thanks for using our library! Just to confirm your qiskit version, is the 'qiskit' version as '0.19.2' or 'qiskit-terra' version as '0.19.2'? 

Here is the version information of my setting:

`{'qiskit-terra': '0.19.2', 'qiskit-aer': '0.10.3', 'qiskit-ignis': '0.7.0', 'qiskit-ibmq-provider': '0.18.3', 'qiskit-aqua': '0.9.5', 'qiskit': '0.34.2', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}`

**Comment by royess** [comment]
The "qiskit" version. And for detailed information:

```python
>>> qiskit.version.QiskitVersion()
{'qiskit-terra': '0.19.2', 'qiskit-aer': '0.10.3', 'qiskit-ignis': '0.7.0', 'qiskit-ibmq-provider': '0.18.3', 'qiskit-aqua': None, 'qiskit': '0.34.2', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}
```

Seems that our version information matches except for "qiskit-aqua".

**Comment by Hanrui-Wang** [comment]
Could you try in `mnist_example.py` line 74: 
  `self.q_device, self.encoder, self.q_layer, self.measure, x, parallel=False)` to see whether it works?

**Comment by royess** [comment]
I tried but the problem remains.

**Comment by Hanrui-Wang** [comment]
Could you show the error log when using `parallel=False`? Thanks!

**Comment by Hanrui-Wang** [comment]
We can also setup a meeting to discuss through Zoom, or wechat (my wechat id is hanrui-wang)

**Comment by royess** [comment]
Thanks! I attach the error log using `parallel=False`. I notice line 3 reads `[2022-03-31 15:59:51.119] Cannot use MIT backend, roll back to open`. I am not sure whether it is related to the problem.

[output_no_parallel.txt](https://github.com/mit-han-lab/torchquantum/files/8387277/output_no_parallel.txt)

(I also sent you a Wechat invitation.)

**Comment by Hanrui-Wang** [comment]
As we discussed offline, the issues occurs in the `qiskit/tools/parallel.py` line 150, the `with` block cannot finish. One work around is to modify the line 316 in `qiskit/assembler/assemble_circuits.py` from 

`experiments_and_pulse_libs = parallel_map(_assemble_circuit, circuits, [run_config])`

to

`experiments_and_pulse_libs = [_assemble_circuit(circ, run_config) for circ in circuits]`

We are currently investigating whether it is the python 3.10 issue. (since the python 3.8 does not have the bug)

**Comment by royess** [comment]
I change my python version to 3.9 and the bug is fixed. I think @Hanrui-Wang 's opinion should be true. Thank you again! (Please feel free to close the issue after doing checks on your side.)

**Comment by Hanrui-Wang** [comment]
Thanks! I think it should be the `concurrent` package problem in python 3.10. I will update the requirements. Thanks again for helping us find this issue!
